#! /usr/bin/env bash

# install required libraries on Ubuntu or other systems that use apt package manager
sudo apt-get install -y \
libexpat1 \ 
libexpat1-dev \
libglib2.0 \ 
libglib2.0-dev \
liblcms2-2 \
liblcms2-dev \
libexif12 \ 
libexif-dev \ 
libgsf-1-def \ 
libjpeg-turbo8-dev \
libpng-dev \ 
libtiff-dev \ 
libgif-dev \ 
liborc-0.4-dev

# Install webp support
cd /tmp
WEBP_VERSION=1.2.2
WEBP_URL=https://storage.googleapis.com/downloads.webmproject.org/releases/webp

wget ${WEBP_URL}/libwebp-${WEBP_VERSION}.tar.gz \
  && tar xzf libwebp-${WEBP_VERSION}.tar.gz \
  && cd libwebp-${WEBP_VERSION} \
  && ./configure \
  && make V=0 \
  && sudo make install

# install libde265 - required for libheif
cd /tmp
LIBDE265_VERSION=1.0.8
LIBDE265_URL=https://github.com/strukturag/libde265/releases/download/v${LIBDE265_VERSION}/libde265-${LIBDE265_VERSION}.tar.gz
wget ${LIBDE265_URL} \
  && tar xzf libde265-${LIBDE265_VERSION}.tar.gz \
  && cd libde265-${LIBDE265_VERSION} \
  && ./autogen.sh \
  && ./configure \
  && make V=0 \
  && sudo make install

# install X265 - required for libheif
cd /tmp
X265_VERSION=3.5
X265_URL=https://bitbucket.org/multicoreware/x265_git/downloads/x265_${X265_VERSION}.tar.gz

wget ${X265_URL} \
  && tar xzf x265_${X265_VERSION}.tar.gz \
  && cd x265_${X265_VERSION} \
  && cmake source \
  && make V=0 \
  && sudo make install

# install libheif  
cd /tmp
LIBHEIF_VERSION=1.12.0
LIBHEIF_URL=https://github.com/strukturag/libheif/releases/download/v${LIBHEIF_VERSION}/libheif-${LIBHEIF_VERSION}.tar.gz
wget ${LIBHEIF_URL} \
  && tar xzf libheif-${LIBHEIF_VERSION}.tar.gz \
  && cd  libheif-${LIBHEIF_VERSION} \
  && ./autogen.sh \
  && ./configure \
  && make V=0 \
  && sudo make install

# compile libvips
cd /tmp
VIPS_VERSION=8.12.2
VIPS_URL=https://github.com/libvips/libvips/releases/download  

RUN wget $VIPS_URL/v$VIPS_VERSION/vips-$VIPS_VERSION.tar.gz \
  && tar xzf vips-$VIPS_VERSION.tar.gz \
  && cd vips-$VIPS_VERSION \
  && ./configure \
  && make V=0 \
  && sudo make install